services:
  - type: web
    name: ghhf-vs-dhhf
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run ghhf_app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --browser.gatherUsageStats false
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_ENABLE_STATIC_SERVING
        value: true